// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/magang/get-token": {
            "get": {
                "description": "Mendapatkan URL untuk login Google OAuth dan mendapatkan refresh token",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Magang"
                ],
                "summary": "Generate login URL untuk developer",
                "responses": {
                    "200": {
                        "description": "HTML link untuk login Google",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/magang/upload": {
            "post": {
                "description": "Upload satu file ZIP berisi CV, Brainmap, Portofolio beserta jawaban pertanyaan umum dan divisi",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Magang"
                ],
                "summary": "Upload dokumen magang",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama mahasiswa",
                        "name": "nama",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NRP mahasiswa",
                        "name": "nrp",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kelompok KP",
                        "name": "kelompok_kp",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pertanyaan umum Q1",
                        "name": "pertanyaan_umum[q1]",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pertanyaan umum Q2",
                        "name": "pertanyaan_umum[q2]",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pertanyaan umum Q3",
                        "name": "pertanyaan_umum[q3]",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "Marketing",
                                "Finance",
                                "IT",
                                "HR",
                                "CMI"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Divisi yang dipilih (min 1, max 3)",
                        "name": "divisi_dipilih",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Soal 1 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q1]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 2 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q2]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 3 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q3]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 4 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q4]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 5 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q5]",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File ZIP berisi CV, Brainmap, Portofolio",
                        "name": "file_zip",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File URL dan data form",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "allOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "error": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "allOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "error": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/shortlink/generate": {
            "post": {
                "description": "buat short link",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link shortener"
                ],
                "summary": "buat short link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL asli yang ingin diperpendek",
                        "name": "link",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nama url (contoh: link:myanimelist.net shortlink: anime)",
                        "name": "shortlink",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ShortLinkDtoRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server or database error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/shortlink/redirect/{shorturl}": {
            "get": {
                "description": "Redirect ke url asli berdasarkan shortlink",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link shortener"
                ],
                "summary": "Redirect ke url asli",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nama link yang diinginkan",
                        "name": "shorturl",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "301": {
                        "description": "Redirected",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server or database error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ShortLinkDtoRes": {
            "type": "object",
            "properties": {
                "shortlink": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "hmtc documentation",
	Description:      "API hmtc link shortener dan user",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
