// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/evaluasi-cmi/submit": {
            "post": {
                "description": "Menerima data evaluasi dalam bentuk form-data dan menyimpannya ke Google Sheets.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Evaluasi CMI 2025"
                ],
                "summary": "Mengunggah hasil evaluasi CMI 2025",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama penilai",
                        "name": "nama",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Departemen penilai",
                        "name": "departemen",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Kejelasan komunikasi",
                        "name": "kejelasan_komunikasi",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Responsivitas",
                        "name": "responsivitas",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Koordinasi kegiatan",
                        "name": "koordinasi_kegiatan",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Profesionalisme",
                        "name": "profesionalisme",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Keterbukaan terhadap feedback",
                        "name": "keterbukaan_feedback",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kualitas dukungan",
                        "name": "kualitas_dukung",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Keterlibatan aktif",
                        "name": "keterlibatan_aktif",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Inovasi \u0026 kreativitas",
                        "name": "inovasi_kreativitas",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Pemahaman tugas",
                        "name": "pemahaman_tugas",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kepatuhan deadline",
                        "name": "kepatuhan_deadline",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Consistensi visual (CD)",
                        "name": "cd_konsistensi_visual",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kesesuaian brief (CD)",
                        "name": "cd_kesesuaian_brief",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Estetika (CD)",
                        "name": "cd_estetika",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kecepatan revisi (CD)",
                        "name": "cd_kecepatan_revisi",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Strategi konten (SM)",
                        "name": "sms_strategi_konten",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Pemahaman audiens (SM)",
                        "name": "sms_audien",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Copywriting/caption (SM)",
                        "name": "sms_caption",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Analitik konten (SM)",
                        "name": "sms_analitik",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kualitas produksi (MP)",
                        "name": "mp_kualitas_produksi",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Konsep (MP)",
                        "name": "mp_konsep",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Inovasi (MP)",
                        "name": "mp_inovasi",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Dokumentasi (MP)",
                        "name": "mp_dokumentasi",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Stabilitas sistem (IT)",
                        "name": "it_stabilitas",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Kemampuan teknis (IT)",
                        "name": "it_teknis",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Keamanan sistem (IT)",
                        "name": "it_keamanan",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "User experience (IT)",
                        "name": "it_ux",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Feedback umum",
                        "name": "umpan_balik_umum",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Saran perbaikan",
                        "name": "saran_perbaikan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Komentar tambahan",
                        "name": "komentar_tambahan",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Evaluasi berhasil disimpan",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Form tidak valid",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Gagal menyimpan ke Google Sheets",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/magang/get-token": {
            "get": {
                "description": "Mendapatkan URL untuk login Google OAuth dan mendapatkan refresh token",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Magang"
                ],
                "summary": "Generate login URL untuk developer",
                "responses": {
                    "200": {
                        "description": "HTML link untuk login Google",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/magang/upload": {
            "post": {
                "description": "Upload satu file ZIP berisi CV, Brainmap, Portofolio beserta jawaban pertanyaan umum dan divisi",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Magang"
                ],
                "summary": "Upload dokumen magang",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama mahasiswa",
                        "name": "nama",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NRP mahasiswa",
                        "name": "nrp",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kelompok KP",
                        "name": "kelompok_kp",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pertanyaan umum Q1",
                        "name": "pertanyaan_umum[q1]",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pertanyaan umum Q2",
                        "name": "pertanyaan_umum[q2]",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pertanyaan umum Q3",
                        "name": "pertanyaan_umum[q3]",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "Marketing",
                                "Finance",
                                "IT",
                                "HR",
                                "CMI"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Divisi yang dipilih (min 1, max 3)",
                        "name": "divisi_dipilih",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Soal 1 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q1]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 2 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q2]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 3 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q3]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 4 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q4]",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Soal 5 Marketing",
                        "name": "pertanyaan_divisi[Marketing][q5]",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File ZIP berisi CV, Brainmap, Portofolio",
                        "name": "file_zip",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File URL dan data form",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "allOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "error": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "allOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "error": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/shortlink/generate": {
            "post": {
                "description": "buat short link",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link shortener"
                ],
                "summary": "buat short link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL asli yang ingin diperpendek",
                        "name": "link",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nama url (contoh: link:myanimelist.net shortlink: anime)",
                        "name": "shortlink",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ShortLinkDtoRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server or database error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/shortlink/redirect/{shorturl}": {
            "get": {
                "description": "Redirect ke url asli berdasarkan shortlink",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link shortener"
                ],
                "summary": "Redirect ke url asli",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nama link yang diinginkan",
                        "name": "shorturl",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "301": {
                        "description": "Redirected",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server or database error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ShortLinkDtoRes": {
            "type": "object",
            "properties": {
                "shortlink": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "HMTC API Documentation",
	Description:      "API Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
