basePath: /api
definitions:
  dto.ShortLinkDtoRes:
    properties:
      shortlink:
        type: string
    type: object
  utils.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      status:
        type: boolean
    type: object
host: localhost:3000
info:
  contact: {}
  description: API hmtc link shortener dan user
  title: hmtc documentation
  version: "1.0"
paths:
  /magang/get-token:
    get:
      description: Mendapatkan URL untuk login Google OAuth dan mendapatkan refresh
        token
      produces:
      - text/html
      responses:
        "200":
          description: HTML link untuk login Google
          schema:
            type: string
      summary: Generate login URL untuk developer
      tags:
      - Magang
  /magang/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload satu file ZIP berisi CV, Brainmap, Portofolio beserta jawaban
        pertanyaan umum dan divisi
      parameters:
      - description: Nama mahasiswa
        in: formData
        name: nama
        required: true
        type: string
      - description: NRP mahasiswa
        in: formData
        name: nrp
        required: true
        type: string
      - description: Kelompok KP
        in: formData
        name: kelompok_kp
        required: true
        type: string
      - description: Pertanyaan umum Q1
        in: formData
        name: pertanyaan_umum[q1]
        required: true
        type: string
      - description: Pertanyaan umum Q2
        in: formData
        name: pertanyaan_umum[q2]
        required: true
        type: string
      - description: Pertanyaan umum Q3
        in: formData
        name: pertanyaan_umum[q3]
        required: true
        type: string
      - collectionFormat: multi
        description: Divisi yang dipilih (min 1, max 3)
        in: formData
        items:
          enum:
          - Marketing
          - Finance
          - IT
          - HR
          - CMI
          type: string
        name: divisi_dipilih
        required: true
        type: array
      - description: Soal 1 Marketing
        in: formData
        name: pertanyaan_divisi[Marketing][q1]
        type: string
      - description: Soal 2 Marketing
        in: formData
        name: pertanyaan_divisi[Marketing][q2]
        type: string
      - description: Soal 3 Marketing
        in: formData
        name: pertanyaan_divisi[Marketing][q3]
        type: string
      - description: Soal 4 Marketing
        in: formData
        name: pertanyaan_divisi[Marketing][q4]
        type: string
      - description: Soal 5 Marketing
        in: formData
        name: pertanyaan_divisi[Marketing][q5]
        type: string
      - description: File ZIP berisi CV, Brainmap, Portofolio
        in: formData
        name: file_zip
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: File URL dan data form
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
      summary: Upload dokumen magang
      tags:
      - Magang
  /shortlink/generate:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: buat short link
      parameters:
      - description: URL asli yang ingin diperpendek
        in: formData
        name: link
        required: true
        type: string
      - description: 'nama url (contoh: link:myanimelist.net shortlink: anime)'
        in: formData
        name: shortlink
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ShortLinkDtoRes'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal server or database error
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                error:
                  type: string
              type: object
      summary: buat short link
      tags:
      - link shortener
  /shortlink/redirect/{shorturl}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Redirect ke url asli berdasarkan shortlink
      parameters:
      - description: nama link yang diinginkan
        in: path
        name: shorturl
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Redirected
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal server or database error
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                error:
                  type: string
              type: object
      summary: Redirect ke url asli
      tags:
      - link shortener
swagger: "2.0"
